#- uses: muinmomin/webhook-action@v1.0.0
name: Rezrecall build and test
run-name: ${{ github.actor }} build + test of Rezrecall monoropo 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Maven build and test
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Notify author about results
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: ${{ secrets.TELL_MARK_WEBHOOK_URL }}
          json: '{ "text": "Completed a build and test of Rezrecall 🚀" }'

