#- uses: muinmomin/webhook-action@v1.0.0
name: Rezrecall build and test
run-name: ${{ github.actor }} build + test of Rezrecall monoropo 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Rezrecall_Build_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Maven build and test
        run: echo "🎉 The job will run unit tests on Rezrecall for ${{ github.event_name }}) event."
      - name: Check out repository code
        uses: actions/checkout@v3
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -U integration-test
      - run: mkdir artifacts-upload && cp target/*.jar artifacts-upload
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: artifacts-upload
      - name: Notify author about results
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: ${{ secrets.TELL_MARK_WEBHOOK_URL }}
          json: '{ "text": "Completed a build and test of Rezrecall 🚀" }'

